$ ->
  # Hide search wrap by default;
  $('.search-wrap').hide()
  $('.toggle-search').on 'click', (e) ->
    # Prevent default link behavior
    e.preventDefault()
    # Stop propagation
    e.stopPropagation()
    # Toggle search-wrap
    $('.search-wrap').slideToggle 500, ->
      # Focus on the search bar
      # When animation is complete
      $('#search-bar').focus()
      return
    return
  # Close the search bar if user clicks anywhere
  $(document).click (e) ->
    searchWrap = $('.search-wrap')
    if !searchWrap.is(e.target) and searchWrap.has(e.target).length == 0
      searchWrap.slideUp 500
    return
  return

# ---
# generated by js2coffee 2.0.3

$('#window').click ->
  sa = $(this).text()
  $(this).text ''
  $(this).addClass 'ball'
  setTimeout (->
    $('#modal').fadeIn()
    $('#close').css 'width', '30px'
    $('#close').css 'height', '30px'
    setTimeout (->
      $('#window').removeClass 'ball'
      $('#window').text sa
      return
    ), 500
    return
  ), 800
  return
$('#close').click ->
  $('#modal').fadeOut()
  $('#close').css 'width', '0px'
  $('#close').css 'height', '0px'
  return